name: Build Test and Publish Nightly Packages

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
    inputs: {}
  push:
    branches:
      - nightly

jobs:
  test-debian-bullseye-aarch64:
    runs-on: ['self-hosted', 'linux', 'arm64']

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: builds-debian-bullseye-aarch64
        path: artifacts/debian-bullseye
        run-id: 8072144494

    - name: Test
      uses: edgedb/edgedb-pkg/integration/linux/test/debian-bullseye@master
      env:
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "debian"
        PKG_PLATFORM_VERSION: "bullseye"
        PKG_PLATFORM_LIBC: ""
        # edb test with -j higher than 1 seems to result in workflow
        # jobs getting killed arbitrarily by Github.
        PKG_TEST_JOBS: 0
        EDGEDB_DEBUG_SERVER: 1
