name: Build Test and Publish a Testing Release

on:
  workflow_dispatch:
    inputs: {}

jobs:
  test-macos-x86_64:
    runs-on: ['macos-14-large']

    steps:
    - run: |
        sysctl -a | grep shm

    - uses: actions/checkout@v4
      with:
        repository: edgedb/edgedb-pkg
        ref: master
        path: edgedb-pkg

    - uses: actions/download-artifact@v4
      with:
        name: builds-macos-x86_64
        path: artifacts/macos-x86_64
        run-id: 8337265753

    - name: Test
      env:
        PKG_SUBDIST: "testing"
        PKG_PLATFORM: "macos"
        PKG_PLATFORM_VERSION: "x86_64"
      run: |
        edgedb-pkg/integration/macos/test.sh
